default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: "/tmp/AuthKey.p8"
    )

    setup_ci if is_ci
    match(type: "appstore", readonly: is_ci, api_key: api_key)
    latest_build = latest_testflight_build_number(api_key: api_key, app_identifier: "com.kihyeon.BalanceEat")
    increment_build_number(build_number: latest_build + 1, xcodeproj: "BalanceEat.xcodeproj")
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "BalanceEat.xcodeproj",
      code_sign_identity: "Apple Distribution",
      profile_name: "match AppStore com.kihyeon.BalanceEat",
      bundle_identifier: "com.kihyeon.BalanceEat",
      team_id: "697ACQDW6C"
    )
    build_app(
      scheme: "BalanceEat",
      export_method: "app-store"
    )
    upload_to_testflight(api_key: api_key)
  end
end
