default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: is_ci)
    increment_build_number(xcodeproj: "BalanceEat.xcodeproj")
    build_app(
      scheme: "BalanceEat",
      export_method: "app-store"
    )
    upload_to_testflight
  end
end
