default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if is_ci
    match(type: "appstore", readonly: is_ci)
    increment_build_number(xcodeproj: "BalanceEat.xcodeproj")
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "BalanceEat.xcodeproj",
      code_sign_identity: "Apple Distribution",
      profile_name: "match AppStore com.kihyeon.BalanceEat",
      bundle_identifier: "com.kihyeon.BalanceEat",
      team_id: "697ACQDW6C"
    )
    build_app(
      scheme: "BalanceEat",
      export_method: "app-store"
    )
    upload_to_testflight
  end
end
